#!/bin/bash

charlemagne=$(pwd)

cd boot/arch/aarch64; make boot; cd $charlemagne

cd kernel; make kernel; cd $charlemagne

aarch64-elf-gcc -T linker.ld -o bertos.elf -ffreestanding -O2 -nostdlib boot/arch/aarch64/boot.o kernel/kernel.o -lgcc

aarch64-elf-objcopy bertos.elf -O binary kernel8.img